version: "3.8"

x-env: &env
    environment:
        POSTGRES_USER: ${DB_USER:-user}
        POSTGRES_PASSWORD: ${DB_PASSWORD:-user}
        POSTGRES_HOST: ${DB_HOST:-postgres}

services:
    postgres:
        <<: *env
        image: postgres:15-alpine3.19
        volumes:
            - postgres:/var/lib/postgresql/data
            - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
        networks:
            - postgres
        stop_grace_period: 1s
networks:
    postgres:
        driver: bridge

volumes:
    postgres:
